# Generated by Django 5.2.6 on 2025-10-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroactividad',
            name='url_visitada',
        ),
        migrations.AddField(
            model_name='registroactividad',
            name='detalles',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles'),
        ),
        migrations.AlterField(
            model_name='registroactividad',
            name='tipo_accion',
            field=models.CharField(choices=[('login', 'Inicio de Sesión'), ('view', 'Consulta de Vista'), ('create', 'Creación de Objeto'), ('update', 'Actualización de Objeto'), ('delete', 'Eliminación de Objeto'), ('export', 'Exportación de Datos'), ('print', 'Impresión de Documento')], max_length=10, verbose_name='Tipo de Acción'),
        ),
    ]
