"""
Django settings for mi_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r497w#dz^fe4mxv^@-w@e=$ig1!7xder4xwfj3+!5vifo=kfc2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['atenea-gob.cloud', 'www.atenea-gob.cloud', '168.231.73.222','127.0.0.1']

# Application definition

INSTALLED_APPS = [
#    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'import_export',
    'core',
    'dashboard',
    'auditoria',
    'atenea',
    'inicio',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditoria.middleware.ActivityLogMiddleware',
]

ROOT_URLCONF = 'mi_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mi_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'safirho_db',
        'USER': 'omar.ramirez',
        'PASSWORD': 'Raal1011.',
        'HOST': '168.231.73.222',
        'PORT': '3306',
    },
    # base de datos de SGB
    'scg_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'scg_db', # Nombre de la base de datos de scg
        'USER': 'omar.ramirez', # O el usuario que tenga acceso
        'PASSWORD': 'Raal1011.',
        'HOST': '168.231.73.222',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# USO DE COOKIES PARA PRD

#SESSION_COOKIE_SECURE = True
#CSRF_COOKIE_SECURE = True


# en mi_backend/settings.py (al final del archivo)

"""JAZZMIN_SETTINGS = {
    # Título del sitio (mostrado en la pestaña del navegador y en el login)
    "site_title": "Agencia Nacional de Aduanas de México",

    # Título en la barra de navegación (puedes usar un HTML simple)
    "site_header": "Atenea",

    # Logo para la pantalla de login
    "site_logo": "core/img/logo.png", # Ruta a tu logo dentro de la carpeta static de una app

    # --- COLORES DE LA INTERFAZ ---
    # Cambia estos códigos hexadecimales por los de tu paleta institucional
    "theme": "litera", # Puedes probar otros temas como "darkly", "litera", "sandstone"

    "custom_css": None,
    "custom_js": None,

    "ui_tweaks": {
        "navbar_small_text": False,
        "footer_small_text": False,
        "body_small_text": False,
        "brand_small_text": False,
        "brand_colour": "navbar-dark", # Color del texto en la barra de navegación
        "accent": "accent-primary",
        "navbar": "navbar-dark", # Estilo de la barra de navegación
        "no_navbar_border": False,
        "navbar_fixed": True,
        "layout_boxed": False,
        "footer_fixed": False,
        "sidebar_fixed": True,
        "sidebar": "sidebar-dark-primary", # Estilo de la barra lateral
        "sidebar_nav_small_text": False,
        "sidebar_disable_expand": False,
        "sidebar_nav_child_indent": False,
        "sidebar_nav_compact_style": False,
        "sidebar_nav_legacy_style": False,
        "sidebar_nav_flat_style": True,
        "theme": "default",
        "dark_mode_theme": None,
        "button_classes": {
            "primary": "btn-primary",
            "secondary": "btn-secondary",
            "info": "btn-info",
            "warning": "btn-warning",
            "danger": "btn-danger",
            "success": "btn-success"
        }
    }
}

# Opcional: para una personalización de colores más detallada
# JAZZMIN_UI_TWEAKS = {
#    "theme": "flatly",
#    "dark_mode_theme": "darkly",
# }
"""
