"""
Django settings for siorh project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""


from pathlib import Path
import importlib.util

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jv6rmkc#@ee793nts78h0_7t(0ygq9yr7(+1@7fwvt7o+tpxkv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['atenea-gob.cloud', 'www.atenea-gob.cloud', '168.231.73.222', '127.0.0.1', '89.116.51.124', 'localhost']

# Application definition

INSTALLED_APPS = [
#    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'corsheaders',
    'rest_framework',  
    'ws_siorh',       

]

if importlib.util.find_spec('import_export'):
    INSTALLED_APPS.append('import_export')

HAS_AUDITORIA = importlib.util.find_spec('auditoria') is not None

if HAS_AUDITORIA:
    INSTALLED_APPS.append('auditoria')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if HAS_AUDITORIA:
    MIDDLEWARE.append('auditoria.middleware.ActivityLogMiddleware')

ROOT_URLCONF = 'siorh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'siorh.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'safirho_db',
        'USER': 'omar.ramirez',
        'PASSWORD': 'Raal1011.',
        'HOST': '168.231.73.222',
        'PORT': '3306',
        'OPTIONS': {
            'connect_timeout': 5,
        },
        'CONN_MAX_AGE': 0,
    },
    # base de datos de SGB
    'scg_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'scg_db', # Nombre de la base de datos de scg
        'USER': 'omar.ramirez', # O el usuario que tenga acceso
        'PASSWORD': 'Raal1011.',
        'HOST': '168.231.73.222',
        'PORT': '3306',
        'OPTIONS': {
            'connect_timeout': 5,
        },
        'CONN_MAX_AGE': 0,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# USO DE COOKIES PARA PRD

#SESSION_COOKIE_SECURE = True
#CSRF_COOKIE_SECURE = True


# en mi_backend/settings.py (al final del archivo)

CORS_ALLOW_ALL_ORIGINS = True 
# O si prefieres ser estricto:
# CORS_ALLOWED_ORIGINS = ["http://localhost:4200", "http://tu-servidor:8060"]